### ISSUE TITLE
Repl - undefined variables

### ISSUE THREAD

**Issue by stas-sl** [adonisjs/adonis-commands#21]
Hi, I'm trying to use repl, but when I'm tying to use some model - it is undefined

````
./ace repl
> User = use('App/Model/User')
{ [Function: User]
  _booted: true,
  '$modelHooks': { beforeCreate: [ [Object] ] },
  '$queryListeners': [],
  globalScope: [ [Function] ] }

> User
{ [Function: User]
  _booted: true,
  '$modelHooks': { beforeCreate: [ [Object] ] },
  '$queryListeners': [],
  globalScope: [ [Function] ] }

> yield User.create({email: 'alice@mail.com', password: '123'})
ReferenceError: User is not defined
    at evalmachine.<anonymous>:2:22
    at Generator.next (<anonymous>)
    at onFulfilled (.../node_modules/co/index.js:65:19)
    at .../node_modules/co/index.js:54:5
    at co (.../node_modules/co/index.js:50:10)
    at evalmachine.<anonymous>:1:1
    at ContextifyScript.Script.runInContext (vm.js:32:29)
    at ContextifyScript.Script.runInNewContext (vm.js:38:15)
    at Object.runInNewContext (vm.js:91:38)
    at REPLServer.evalCommand (.../node_modules/adonis-commands/src/Repl/index.js:54:10)
````

**Comment by stas-sl** [comment]
Sorry, smth was wrong on my end
